### ISSUE TITLE
JSON files give an error

### ISSUE THREAD

**Issue by chanux** [mephux/vim-jsfmt#11]
Is there anyway to ignore json files or better yet, run jsfmt with --json option on json files?

**Comment by mephux** [comment]
I'll look to see if we can add a type detection for json. Shouldn;t be too difficult.

**Comment by mephux** [comment]
@chanux ok, just looked into this.. if the ft=json it will now add the --json flag. Unfortunately there isn't a great way to detect if its javascript or json.

**Comment by chanux** [comment]
For anyone wondering how to have json files treated appropriately, you'd need to add following to your vimrc

`autocmd BufNewFile,BufRead *.json set ft=json`

Note: There's this trick to json files and as javascript and have native syntax highlighting on. This breaks it so you'd need a plugin for that.
