### ISSUE TITLE
noticable delay when run from vim, but not on the commandline

### ISSUE THREAD

**Issue by cschep** [mephux/vim-jsfmt#13]
I'm noticing a delay that is long enough to really break up the flow when enabling it on save. If I run jsmt from the command line on the same file it doesn't seem to stutter at all.

is it possible that it's running on the entire directory or something?

Thanks! I've become super dependent upon the wonderful gofmt that I miss it while writing JavaScript in vim.

**Comment by mephux** [comment]
@cschep with the new jobs feature of vim 8 i'm going to try and get this async
